SELECT 
su.DESC_SUCURSAL
,zn.DESC_ZONA
,ciu.DESC_CIUDAD
,pro.DESC_PROVINCIA
,SUM(det.TOTAL_VTA_SIN_IVA) TOTAL_VENTA_S_IVA
,SUM(det.TOTAL_VTA_CON_IVA) TOTAL_VENTA_C_IVA
FROM sucursal su
 INNER JOIN zona zn on su.ID_ZONA = zn.ID_ZONA
 	INNER JOIN ciudad ciu on zn.ID_CIUDAD = ciu.ID_CIUDAD
 	 INNER JOIN provincia pro on ciu.ID_PROVINCIA = pro.ID_PROVINCIA
 	  INNER JOIN cab_vta vta on su.ID_SUCURSAL = vta.ID_SUCURSAL
 	   INNER JOIN detalle_vta det on vta.ID_CAB_VTA = det.ID_CAB_VTA
 GROUP BY 
 su.DESC_SUCURSAL
,zn.DESC_ZONA
,ciu.DESC_CIUDAD
,pro.DESC_PROVINCIA;